#!/bin/bash

#USAGE: ./808compile <.mp3 sample file>
# at this stage the program assumes that the files "808.wav", "Kck.wav", "Hs.wav", and "Ot.wav"
# already exist and have been driven from previous events in the simulation.

#NOTE: USING ECASOUND, A WRAPPER FOR THE SoX Sound Exchange engine

./ecasound -c -r \
    -a:1 -i $1 -ea:80 \
    -a:2 -i 808.wav -ea:100 \
    -a:3 -i Kck.wav -ea:70 \
    -a:4 -i Hs.wav -ea:90 \
    -a:5 -i Ot.wav -ea:65 \
    -a:1,2,3,4,5 -o loop,9 \
    -a:6 -i loop,9 \
    -a:6 -o beat_326_.wav
