#!/bin/bash

#USAGE: ./generateMIDI <.mp3> <mode>

#$1 = mp3file     $2 = mode
count=1

if [ $2 -eq 1 ]
then
    #it converts the existing beat to midi notes and attempts to change
    #the requisite config file
    python ./aubio.py $1

else
    a=( Pad_Resources/* )
    randf=()

    #gets the sample BPM
    python ./python/demo/demo_bpm_extract.py $1 >> bpm_temp.txt
    bpm = $( cat bpm_temp.txt )
    rm bpm_temp.txt

    # take user sample and make midi file for bassline
    args = $( cat Config/808_config.txt )
    python ./PhraseGenerator.py $bpm $args
    java MidiConverter 808_.mid 808.mid

    # take user sample and make midi file for kick pattern
    args = $( cat Config/kick_config.txt )
    python ./PhraseGenerator.py $bpm $args
    java MidiConverter Kck_.mid Kck.mid

    # take user sample and make midi file for high hats
    args = $( cat Config/Hs_config.txt )
    python ./PhraseGenerator.py $bpm $args
    java MidiConverter Hs_.mid Hs.mid

    # take user sample and make midi file for claps
    args = $( cat Config/Ot_config.txt )
    python ./PhraseGenerator.py $bpm $args
    java MidiConverter Ot_.mid Ot.mid

    done
fi
