#!/bin/bash

#USAGE: ./render808 <MIDI file> <N>

#$1 = midi_filename     $2 = N
count=1

for n in $(seq $2); do
    echo "# $count"
    # RANDOMLY PICK DRUMKIT FOR 808
    ./rand_rsc

    # RENDER MIDI FILE TO WAV WITH MRSWATSON
    outfile="out_"
    outfile+=$( echo $count)
    outfile+=".wav"

    ./mrswatson -p 808 -m $1 -o $outfile --quiet

    # RETRIEVE THE RANDOM RESOURCE AND REPLACE IT
    ./retr_rsc

    # ITERATE THE COUNTER FOR OUTPUT FILE
    count=$((count+1))
done
